In [1]:
import nfn_crawring as nf

CORP = ['063570', '한국전자금융']

In [2]:
# 한국전자금융 연간 손익계산서
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.FS,
             subType=nf.FSType.IS,
             period=nf.Period.YEAR)

https://navercomp.wisereport.co.kr/v2/company/cF3002.aspx?cmp_cd=063570&frq=0&rpt=0&finGubun=MAIN&frqTyp=0&cn=&encparam=cE9KN0RLKy96ZmRnWnFnUWkzUkpodz09

,account_nm,2018/12,2019/12,2020/12,2021/12,2022/12
0,매출액(수익),2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
1,*내수,2878.280000,2770.320000,NaN,2382.230000,2886.220000
2,*수출,65.950000,58.440000,NaN,1.410000,2.910000
3,....제품매출액,0.604177,0.159183,NaN,31.180260,60.965554
4,....상품매출액,692.256471,506.510165,287.280901,302.577220,288.685799
...,...,...,...,...,...,...
239,*희석주당순이익,NaN,NaN,NaN,NaN,NaN
240,*(지배주주지분)주당계속사업이익,702.000000,77.000000,165.000000,311.000000,282.000000
241,*(지배주주지분)주당순이익,702.000000,89.000000,114.000000,306.000000,282.000000
242,*(지배주주지분)희석주당계속사업이익,NaN,NaN,NaN,NaN,NaN
243,*(지배주주지분)희석주당순이익,NaN,NaN,NaN,NaN,NaN

In [3]:
# 한국전자금융 분기 손익계산서
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.FS,
             subType=nf.FSType.IS,
             period=nf.Period.QUARTER)

https://navercomp.wisereport.co.kr/v2/company/cF3002.aspx?cmp_cd=063570&frq=1&rpt=0&finGubun=MAIN&frqTyp=1&cn=&encparam=UnRSbFZkeXNMOWFreWNHNFVIZlBWUT09

,account_nm,2022/09,2022/12,2023/03,2023/06,2023/09
0,매출액(수익),722.168679,847.499866,775.627411,892.707520,940.858114
1,*내수,722.170000,NaN,NaN,891.210000,940.830000
2,*수출,NaN,NaN,NaN,1.490000,0.030000
3,....제품매출액,4.105637,32.288882,8.534880,8.600161,4.677022
4,....상품매출액,69.751903,110.447931,82.861370,160.101081,197.158696
...,...,...,...,...,...,...
239,*희석주당순이익,NaN,NaN,NaN,NaN,NaN
240,*(지배주주지분)주당계속사업이익,57.000000,NaN,NaN,127.000000,54.000000
241,*(지배주주지분)주당순이익,57.000000,NaN,NaN,127.000000,54.000000
242,*(지배주주지분)희석주당계속사업이익,NaN,NaN,NaN,NaN,NaN
243,*(지배주주지분)희석주당순이익,NaN,NaN,NaN,NaN,NaN

In [4]:
# 한국전자금융 연간 재무상태표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.FS,
             subType=nf.FSType.BS,
             period=nf.Period.YEAR)

https://navercomp.wisereport.co.kr/v2/company/cF3002.aspx?cmp_cd=063570&frq=0&rpt=1&finGubun=MAIN&frqTyp=0&cn=&encparam=UzJOdmF6cjIyMEJhVUtFNWJ6dFFPQT09

,account_nm,2018/12,2019/12,2020/12,2021/12,2022/12
0,자산총계,4108.511522,4539.485248,4779.355936,4887.530411,4978.971116
1,유동자산,2376.606467,2202.974762,2107.826065,1895.404427,1907.926225
2,....재고자산,37.304926,25.796422,38.566846,11.852604,14.765065
3,........상품,35.359430,24.977710,37.650820,11.852600,14.765070
4,........제품,0.393290,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
246,수권주식수,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
247,1주당금액,500.000000,500.000000,500.000000,500.000000,500.000000
248,발행주식수,34646.000000,34148.000000,34148.000000,34148.000000,34148.000000
249,보통주,34646.000000,34148.000000,34148.000000,34148.000000,34148.000000
250,우선주,NaN,NaN,NaN,NaN,NaN

In [5]:
# 한국전자금융 분기 재무상태표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.FS,
             subType=nf.FSType.BS,
             period=nf.Period.QUARTER)

https://navercomp.wisereport.co.kr/v2/company/cF3002.aspx?cmp_cd=063570&frq=1&rpt=1&finGubun=MAIN&frqTyp=1&cn=&encparam=ZVl2Smp3SUx0TWxNeGxsSXZVRm5wZz09

,account_nm,2022/09,2022/12,2023/03,2023/06,2023/09
0,자산총계,4786.461481,4978.971116,4967.224414,4999.863125,5436.884203
1,유동자산,1864.110869,1907.926225,1953.478573,1895.475551,2290.556429
2,....재고자산,19.271134,14.765065,20.455892,21.094209,58.418302
3,........상품,19.271130,14.765070,20.455890,21.094210,58.418300
4,........제품,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
246,수권주식수,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
247,1주당금액,500.000000,500.000000,500.000000,500.000000,500.000000
248,발행주식수,34148.000000,34148.000000,34148.000000,34148.000000,34148.000000
249,보통주,34148.000000,34148.000000,34148.000000,34148.000000,34148.000000
250,우선주,NaN,NaN,NaN,NaN,NaN

In [6]:
# 한국전자금융 연간 현금흐름표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.FS,
             subType=nf.FSType.CF,
             period=nf.Period.YEAR)

https://navercomp.wisereport.co.kr/v2/company/cF3002.aspx?cmp_cd=063570&frq=0&rpt=2&finGubun=MAIN&frqTyp=0&cn=&encparam=SmszU0VGSzJRTGxWL3d4Tzh1VHNOUT09

,account_nm,2018/12,2019/12,2020/12,2021/12,2022/12
0,영업활동으로인한현금흐름,198.101716,516.091543,527.096523,662.753346,700.285728
1,....당기순이익,122.844050,9.697600,20.268460,90.414880,86.648560
2,....법인세비용차감전계속사업이익,NaN,NaN,NaN,NaN,NaN
3,....현금유출이없는비용등가산,451.195860,677.758010,691.170160,717.282960,806.890670
4,........금융비용,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
307,연결범위변동으로인한현금의증가,NaN,NaN,NaN,NaN,NaN
308,환율변동효과,-0.072424,0.099782,-0.018040,-0.049413,-0.161770
309,현금및현금성자산의증가,-146.059453,-201.341863,-40.799688,-174.863560,-226.926020
310,기초현금및현금성자산,2077.292059,1931.232607,1729.890744,1689.091055,1514.227495
311,기말현금및현금성자산,1931.232607,1729.890744,1689.091055,1514.227495,1287.301476

In [7]:
# 한국전자금융 분기 현금흐름표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.FS,
             subType=nf.FSType.CF,
             period=nf.Period.QUARTER)

https://navercomp.wisereport.co.kr/v2/company/cF3002.aspx?cmp_cd=063570&frq=1&rpt=2&finGubun=MAIN&frqTyp=1&cn=&encparam=bmhrSEJqOThkSE0zVjRWeSswVENYZz09

,account_nm,2022/09,2022/12,2023/03,2023/06,2023/09
0,영업활동으로인한현금흐름,196.468496,165.176665,15.090131,195.806000,181.936979
1,....당기순이익,17.188890,46.311990,15.844030,39.327210,15.583770
2,....법인세비용차감전계속사업이익,NaN,NaN,NaN,NaN,NaN
3,....현금유출이없는비용등가산,192.670580,224.608640,196.010360,210.778440,207.618670
4,........금융비용,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
307,연결범위변동으로인한현금의증가,NaN,NaN,NaN,NaN,NaN
308,환율변동효과,0.095420,-0.074358,0.035460,-0.171597,-0.017908
309,현금및현금성자산의증가,-124.196574,-125.454189,22.354094,-69.439493,262.730772
310,기초현금및현금성자산,1536.952239,1412.755665,1287.301476,1309.655570,1240.216076
311,기말현금및현금성자산,1412.755665,1287.301476,1309.655570,1240.216076,1502.946848

In [8]:
# 한국전자금융 연간 수익성 투자지표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.IV,
             subType=nf.IVType.PROFIT,
             period=nf.Period.YEAR)

https://navercomp.wisereport.co.kr/v2/company/cF4002.aspx?cmp_cd=063570&frq=0&rpt=1&finGubun=MAIN&frqTyp=0&cn=&encparam=ay9rb0E3a3BvZzJQMGJyakl3d3Bldz09

,account_nm,2018/12,2019/12,2020/12,2021/12,2022/12
0,매출총이익률,79.780000,83.632000,90.409000,88.657000,90.187000
1,매출총이익＜당기＞,2348.899546,2332.629187,2042.071070,2113.267473,2605.634518
2,매출액＜당기＞,2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
3,영업이익률,8.462000,5.583000,6.279000,5.994000,6.539000
4,영업이익＜당기＞,249.126770,155.707643,141.824204,142.876328,188.910947
5,매출액＜당기＞,2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
6,순이익률,4.172000,0.348000,0.897000,3.793000,2.999000
7,당기순이익＜당기＞,122.844050,9.697604,20.268465,90.414877,86.648562
8,매출액＜당기＞,2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
9,EBITDA마진율,17.923000,22.141000,28.974000,29.921000,27.621000
10,EBITDA＜당기＞,527.699970,617.563323,654.427134,713.218498,797.994567
11,매출액＜당기＞,2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
12,ROE,15.112000,1.720000,2.235000,5.791000,5.042000
13,당기순이익(지배)＜당기＞,210.404653,26.839986,34.573112,92.660699,85.572728
14,자본총계(지배)＜전기＞,1209.742036,1574.867696,1545.723183,1548.714022,1651.303981
15,자본총계(지배)＜당기＞,1574.867696,1545.723183,1548.714022,1651.303981,1742.938400
16,ROA,3.102000,0.224000,0.435000,1.871000,1.756000
17,당기순이익＜당기＞,122.844050,9.697604,20.268465,90.414877,86.648562
18,자산총계＜전기＞,3812.855626,4108.511522,4539.485248,4779.355936,4887.530411
19,자산총계＜당기＞,4108.511522,4539.485248,4779.355936,4887.530411,4978.971116
20,ROIC,0.181800,2.277300,4.619600,6.403400,6.852000
21,NOPLAT,2.409771,44.729263,106.218728,153.884805,178.290920
22,IC,1324.862617,1964.121525,2299.287700,2403.152661,2602.012501

In [9]:
# 한국전자금융 분기 수익성 투자지표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.IV,
             subType=nf.IVType.PROFIT,
             period=nf.Period.QUARTER)

https://navercomp.wisereport.co.kr/v2/company/cF4002.aspx?cmp_cd=063570&frq=1&rpt=1&finGubun=MAIN&frqTyp=1&cn=&encparam=K0lsNmJOdmFVQ3BIdGkrK2xjRGNrUT09

,account_nm,2022/09,2022/12,2023/03,2023/06,2023/09
0,매출총이익률,91.847000,85.405000,90.320000,83.546000,80.559000
1,매출총이익＜당기＞,663.289710,723.808740,700.548780,745.819815,757.949980
2,매출액＜당기＞,722.168679,847.499866,775.627411,892.707520,940.858114
3,영업이익률,6.059000,7.487000,6.489000,8.282000,6.918000
4,영업이익＜당기＞,43.754863,63.450823,50.328954,73.936257,65.088423
5,매출액＜당기＞,722.168679,847.499866,775.627411,892.707520,940.858114
6,순이익률,2.380000,5.465000,2.043000,4.405000,1.656000
7,당기순이익＜당기＞,17.188888,46.311990,15.844030,39.327205,15.583780
8,매출액＜당기＞,722.168679,847.499866,775.627411,892.707520,940.858114
9,EBITDA마진율,27.670000,25.114000,26.079000,25.542000,23.617000
10,EBITDA＜당기＞,199.823473,212.845333,202.275294,228.019217,222.199913
11,매출액＜당기＞,722.168679,847.499866,775.627411,892.707520,940.858114
12,ROE,4.241000,5.042000,5.957000,6.885000,6.773000
13,당기순이익(지배)＜당기＞,68.911693,85.572728,99.664785,117.374208,116.353794
14,자본총계(지배)＜전기＞,1659.337847,1669.699756,1742.938400,1726.774765,1750.128168
15,자본총계(지배)＜당기＞,1669.699756,1742.938400,1726.774765,1750.128168,1765.895209
16,ROA,1.481000,1.756000,2.011000,2.376000,2.290000
17,당기순이익＜당기＞,70.812070,86.648563,101.122657,118.672114,117.067005
18,자산총계＜전기＞,4991.244306,4786.461481,4978.971116,4967.224414,4999.863125
19,자산총계＜당기＞,4786.461481,4978.971116,4967.224414,4999.863125,5436.884203
20,ROIC,1.538800,2.676100,1.580000,2.343300,1.715400
21,NOPLAT,36.563145,69.635036,42.905297,65.636244,48.452582
22,IC,2375.946460,2602.012501,2715.479004,2800.985450,2824.475428

In [10]:
# 한국전자금융 연간 성장성 투자지표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.IV,
             subType=nf.IVType.GROWTH,
             period=nf.Period.YEAR)

https://navercomp.wisereport.co.kr/v2/company/cF4002.aspx?cmp_cd=063570&frq=0&rpt=2&finGubun=MAIN&frqTyp=0&cn=&encparam=UjNqTkJsVEdveXg3bGZvRGx2Wjkzdz09

   account_nm      2018/12      2019/12      2020/12      2021/12      2022/12
0      매출액증가율    22.145000    -5.267000   -19.019000     5.531000    21.207000
1     매출액＜전기＞  2410.437357  2944.234822  2789.171679  2258.706331  2383.643637
2     매출액＜당기＞  2944.234822  2789.171679  2258.706331  2383.643637  2889.132455
3     영업이익증가율    18.316000   -37.499000    -8.916000     0.742000    32.220000
4    영업이익＜전기＞   210.561320   249.126770   155.707643   141.824204   142.876328
5    영업이익＜당기＞   249.126770   155.707643   141.824204   142.876328   188.910947
6      순이익증가율   -25.237000   -92.106000   109.005000   346.086000    -4.166000
7   당기순이익＜전기＞   164.310818   122.844050     9.697604    20.268465    90.414877
8   당기순이익＜당기＞   122.844050     9.697604    20.268465    90.414877    86.648562
9      총자산증가율     7.754000    10.490000     5.284000     2.263000     1.871000
10   자산총계＜전기＞  3812.855626  4108.511522  4539.485248  4779.355936  4887.530411
11   자산총계＜당기＞  4108.511522  4539.485248  4779.355936  4887.530411  4978.971116
12    유동자산증가율    -4.910000    -7.306000    -4.319000   -10.078000     0.661000
13   유동자산＜전기＞  2499.328323  2376.606467  2202.974762  2107.826065  1895.404427
14   유동자산＜당기＞  2376.606467  2202.974762  2107.826065  1895.404427  1907.926225
15    유형자산증가율    22.716000    36.291000    21.610000    -3.319000     3.428000
16   유형자산＜전기＞   690.117946   846.887883  1154.232074  1403.666704  1357.076968
17   유형자산＜당기＞   846.887883  1154.232074  1403.666704  1357.076968  1403.598439
18    자기자본증가율     5.013000    -2.803000    -1.739000     5.670000     5.570000
19   자본총계＜전기＞  1571.063930  1649.827529  1603.578279  1575.693761  1665.042647
20   자본총계＜당기＞  1649.827529  1603.578279  1575.693761  1665.042647  1757.783841

In [11]:
# 한국전자금융 분기 성장성 투자지표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.IV,
             subType=nf.IVType.GROWTH,
             period=nf.Period.QUARTER)

https://navercomp.wisereport.co.kr/v2/company/cF4002.aspx?cmp_cd=063570&frq=1&rpt=2&finGubun=MAIN&frqTyp=1&cn=&encparam=dHYxUVpmbThVWXZVYi9idGdWNVBqdz09

   account_nm      2022/09      2022/12      2023/03      2023/06      2023/09
0      매출액증가율    -0.370000    17.355000    -8.481000    15.095000     5.394000
1     매출액＜전기＞   724.847679   722.168679   847.499866   775.627411   892.707520
2     매출액＜당기＞   722.168679   847.499866   775.627411   892.707520   940.858114
3     영업이익증가율   -23.132000    45.014000   -20.680000    46.906000   -11.967000
4    영업이익＜전기＞    56.921969    43.754863    63.450823    50.328954    73.936257
5    영업이익＜당기＞    43.754863    63.450823    50.328954    73.936257    65.088423
6      순이익증가율   -21.071000   169.430000   -65.788000   148.215000   -60.374000
7   당기순이익＜전기＞    21.777748    17.188888    46.311990    15.844030    39.327205
8   당기순이익＜당기＞    17.188888    46.311990    15.844030    39.327205    15.583780
9      총자산증가율    -4.103000     4.022000    -0.236000     0.657000     8.741000
10   자산총계＜전기＞  4991.244306  4786.461481  4978.971116  4967.224414  4999.863125
11   자산총계＜당기＞  4786.461481  4978.971116  4967.224414  4999.863125  5436.884203
12    유동자산증가율    -5.152000     2.350000     2.388000    -2.969000    20.843000
13   유동자산＜전기＞  1965.371020  1864.110869  1907.926225  1953.478573  1895.475551
14   유동자산＜당기＞  1864.110869  1907.926225  1953.478573  1895.475551  2290.556429
15    유형자산증가율     0.947000     2.999000    -0.203000     3.484000     3.504000
16   유형자산＜전기＞  1349.954869  1362.735083  1403.598439  1400.753214  1449.556107
17   유형자산＜당기＞  1362.735083  1403.598439  1400.753214  1449.556107  1500.349245
18    자기자본증가율     0.604000     4.401000    -0.924000     1.388000     1.238000
19   자본총계＜전기＞  1673.580362  1683.692291  1757.783841  1741.535612  1765.699530
20   자본총계＜당기＞  1683.692291  1757.783841  1741.535612  1765.699530  1787.564764

In [12]:
# 한국전자금융 연간 안정성 투자지표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.IV,
             subType=nf.IVType.STABILITY,
             period=nf.Period.YEAR)

https://navercomp.wisereport.co.kr/v2/company/cF4002.aspx?cmp_cd=063570&frq=0&rpt=3&finGubun=MAIN&frqTyp=0&cn=&encparam=dHYxUVpmbThVWXZVYi9idGdWNVBqdz09

   account_nm      2018/12      2019/12      2020/12      2021/12      2022/12
0        부채비율   149.027000   183.085000   203.318000   193.538000   183.253000
1        부채총계  2458.683993  2935.906969  3203.662175  3222.487765  3221.187275
2        자본총계  1649.827529  1603.578279  1575.693761  1665.042647  1757.783841
3      유동부채비율   114.368000   133.468000   143.300000   135.963000   138.855000
4        유동부채  1886.874115  2140.270689  2257.971364  2263.835856  2440.763296
5        자본총계  1649.827529  1603.578279  1575.693761  1665.042647  1757.783841
6     비유동부채비율    34.659000    49.616000    60.017000    57.575000    44.398000
7       비유동부채   571.809878   795.636280   945.690811   958.651909   780.423979
8        자본총계  1649.827529  1603.578279  1575.693761  1665.042647  1757.783841
9       순부채비율    -0.084000    48.788000    68.824000    82.767000    80.661000
10        순부채    -1.387387   782.352237  1084.458992  1378.111550  1417.841657
11       자본총계  1649.827529  1603.578279  1575.693761  1665.042647  1757.783841
12       유동비율   125.955000   102.930000    93.350000    83.725000    78.169000
13       유동자산  2376.606467  2202.974762  2107.826065  1895.404427  1907.926225
14       유동부채  1886.874115  2140.270689  2257.971364  2263.835856  2440.763296
15       당좌비율   120.867000   100.244000    89.380000    83.127000    77.454000
16       당좌자산  2280.602253  2145.487934  2018.185282  1881.851814  1890.461159
17       유동부채  1886.874115  2140.270689  2257.971364  2263.835856  2440.763296
18     이자보상배율     3.929600     1.906910     1.825390     1.563030     1.770100
19       영업이익   249.126770   155.707643   141.824204   142.876328   188.910947
20    영업외이자비용    63.397540    81.654310    77.695350    91.409910   106.723020
21    금융비용부담률     2.153000     2.928000     3.440000     3.835000     3.694000
22    영업외이자비용    63.397540    81.654310    77.695350    91.409910   106.723020
23        매출액  2944.234822  2789.171679  2258.706331  2383.643637  2889.132455
24      자본유보율  1044.056000  1042.107000  1043.462000  1102.846000  1158.709000
25  자본잉여금＜당기＞   744.616140   744.617440   758.620390   762.697570   762.697570
26  이익잉여금＜당기＞  1063.988316  1034.662407  1022.972599  1120.286460  1215.666788
27    자본금＜당기＞   173.228640   170.738640   170.738640   170.738640   170.738640

In [13]:
# 한국전자금융 분기 안정성 투자지표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.IV,
             subType=nf.IVType.STABILITY,
             period=nf.Period.QUARTER)

https://navercomp.wisereport.co.kr/v2/company/cF4002.aspx?cmp_cd=063570&frq=1&rpt=3&finGubun=MAIN&frqTyp=1&cn=&encparam=M3lzMmc5WjByd3hvUlFkZEtkd1lFZz09

   account_nm      2022/09      2022/12      2023/03      2023/06      2023/09
0        부채비율   184.284000   183.253000   185.221000   183.166000   204.150000
1        부채총계  3102.769190  3221.187275  3225.688802  3234.163595  3649.319440
2        자본총계  1683.692291  1757.783841  1741.535612  1765.699530  1787.564764
3      유동부채비율   143.314000   138.855000   141.815000   140.134000   162.411000
4        유동부채  2412.962918  2440.763296  2469.756704  2474.352107  2903.198614
5        자본총계  1683.692291  1757.783841  1741.535612  1765.699530  1787.564764
6     비유동부채비율    40.970000    44.398000    43.406000    43.032000    41.740000
7       비유동부채   689.806272   780.423979   755.932098   759.811490   746.120826
8        자본총계  1683.692291  1757.783841  1741.535612  1765.699530  1787.564764
9       순부채비율    79.006000    80.661000    86.584000    88.318000    87.116000
10        순부채  1330.224213  1417.841657  1507.884629  1559.437672  1557.261929
11       자본총계  1683.692291  1757.783841  1741.535612  1765.699530  1787.564764
12       유동비율    77.254000    78.169000    79.096000    76.605000    78.898000
13       유동자산  1864.110869  1907.926225  1953.478573  1895.475551  2290.556429
14       유동부채  2412.962918  2440.763296  2469.756704  2474.352107  2903.198614
15       당좌비율    76.455000    77.454000    78.199000    75.752000    76.655000
16       당좌자산  1844.839743  1890.461159  1931.322680  1874.381342  2225.438130
17       유동부채  2412.962918  2440.763296  2469.756704  2474.352107  2903.198614
18     이자보상배율     1.629490     2.128170     1.425100     1.977820     1.812510
19       영업이익    43.754863    63.450823    50.328954    73.936257    65.088423
20    영업외이자비용    26.851850    29.814780    35.316060    37.382790    35.910680
21    금융비용부담률     3.718000     3.518000     4.553000     4.188000     3.817000
22    영업외이자비용    26.851850    29.814780    35.316060    37.382790    35.910680
23        매출액   722.168679   847.499866   775.627411   892.707520   940.858114
24      자본유보율  1117.496000  1158.709000  1148.498000  1161.217000  1170.654000
25  자본잉여금＜당기＞   762.697570   762.697570   762.697570   762.697570   762.390840
26  이익잉여금＜당기＞  1145.299346  1215.666788  1198.232008  1219.949200  1236.367654
27    자본금＜당기＞   170.738640   170.738640   170.738640   170.738640   170.738640

In [14]:
# 한국전자금융 연간 활동성 투자지표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.IV,
             subType=nf.IVType.ACTIVITY,
             period=nf.Period.YEAR)

https://navercomp.wisereport.co.kr/v2/company/cF4002.aspx?cmp_cd=063570&frq=0&rpt=4&finGubun=MAIN&frqTyp=0&cn=&encparam=MGNoQlNKZnpXVXFaeGZ0emRONU9IZz09

,account_nm,2018/12,2019/12,2020/12,2021/12,2022/12
0,총자산회전율,0.743370,0.645040,0.484760,0.493160,0.585640
1,매출액(수익),2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
2,자산총계＜전기＞,3812.855626,4108.511522,4539.485248,4779.355936,4887.530411
3,자산총계＜당기＞,4108.511522,4539.485248,4779.355936,4887.530411,4978.971116
4,자기자본회전율,1.828210,1.714620,1.420900,1.471050,1.688160
5,매출액＜당기＞,2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
6,자본총계＜당기＞,1649.827529,1603.578279,1575.693761,1665.042647,1757.783841
7,자본총계＜전기＞,1571.063930,1649.827529,1603.578279,1575.693761,1665.042647
8,순운전자본회전율,-155.258060,143.016680,38.561780,49.566640,54.685850
9,매출액＜당기＞,2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
10,..순운전자본＜당기＞,-14.689018,53.693863,63.453540,32.725803,72.937078
11,..순운전자본＜전기＞,-23.237964,-14.689018,53.693863,63.453540,32.725803
12,유형자산회전율,3.831130,2.787610,1.766060,1.726810,2.093060
13,매출액＜당기＞,2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
14,유형자산＜당기＞,846.887883,1154.232074,1403.666704,1357.076968,1403.598439
15,유형자산＜전기＞,690.117946,846.887883,1154.232074,1403.666704,1357.076968
16,매출채권회전율,11.516930,10.392530,8.756400,9.435650,9.693510
17,매출액(수익),2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
18,........장기매출채권,NaN,NaN,NaN,NaN,NaN
19,........매출채권＜전기＞,242.742140,268.546030,268.218660,247.679490,257.562470
20,........매출채권＜당기＞,268.546030,268.218660,247.679490,257.562470,338.534040
21,재고자산회전율,97.706770,88.402920,70.186190,94.552540,217.083800
22,매출액(수익),2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
23,....재고자산＜전기＞,22.961824,37.304926,25.796422,38.566846,11.852604
24,....재고자산＜당기＞,37.304926,25.796422,38.566846,11.852604,14.765065
25,매입채무회전율,50.834290,55.994810,49.316470,56.100090,57.558130
26,매출액(수익),2944.234822,2789.171679,2258.706331,2383.643637,2889.132455
27,........장기매입채무,NaN,NaN,NaN,NaN,NaN
28,........매입채무＜전기＞,66.156140,49.680420,49.942090,41.658390,43.319850
29,........매입채무＜당기＞,49.680420,49.942090,41.658390,43.319850,57.070230

In [15]:
# 한국전자금융 분기 활동성 투자지표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.IV,
             subType=nf.IVType.ACTIVITY,
             period=nf.Period.QUARTER)

https://navercomp.wisereport.co.kr/v2/company/cF4002.aspx?cmp_cd=063570&frq=1&rpt=4&finGubun=MAIN&frqTyp=1&cn=&encparam=TDl6TDFweDFqMzhoS1pTb0xoSmExdz09

,account_nm,2022/09,2022/12,2023/03,2023/06,2023/09
0,총자산회전율,0.147720,0.173570,0.155960,0.179130,0.180300
1,매출액(수익),722.168679,847.499866,775.627411,892.707520,940.858114
2,자산총계＜전기＞,4991.244306,4786.461481,4978.971116,4967.224414,4999.863125
3,자산총계＜당기＞,4786.461481,4978.971116,4967.224414,4999.863125,5436.884203
4,자기자본회전율,0.430210,0.492520,0.443300,0.509060,0.529570
5,매출액＜당기＞,722.168679,847.499866,775.627411,892.707520,940.858114
6,자본총계＜당기＞,1683.692291,1757.783841,1741.535612,1765.699530,1787.564764
7,자본총계＜전기＞,1673.580362,1683.692291,1757.783841,1741.535612,1765.699530
8,순운전자본회전율,13.468180,15.174380,5.601400,4.565380,4.995670
9,매출액＜당기＞,722.168679,847.499866,775.627411,892.707520,940.858114
10,..순운전자본＜당기＞,38.764314,72.937078,204.003719,187.072908,189.596675
11,..순운전자본＜전기＞,68.476410,38.764314,72.937078,204.003719,187.072908
12,유형자산회전율,0.532440,0.612720,0.553160,0.626390,0.637890
13,매출액＜당기＞,722.168679,847.499866,775.627411,892.707520,940.858114
14,유형자산＜당기＞,1362.735083,1403.598439,1400.753214,1449.556107,1500.349245
15,유형자산＜전기＞,1349.954869,1362.735083,1403.598439,1400.753214,1449.556107
16,매출채권회전율,2.666900,2.773470,2.261040,2.238380,1.944750
17,매출액(수익),722.168679,847.499866,775.627411,892.707520,940.858114
18,........장기매출채권,NaN,NaN,NaN,NaN,NaN
19,........매출채권＜전기＞,268.963490,272.614430,338.534040,347.547660,450.089470
20,........매출채권＜당기＞,272.614430,338.534040,347.547660,450.089470,517.498540
21,재고자산회전율,42.987900,49.799910,44.043520,42.970170,23.665660
22,매출액(수익),722.168679,847.499866,775.627411,892.707520,940.858114
23,....재고자산＜전기＞,14.327563,19.271134,14.765065,20.455892,21.094209
24,....재고자산＜당기＞,19.271134,14.765065,20.455892,21.094209,58.418302
25,매입채무회전율,26.004440,18.974450,15.290730,15.328270,11.821030
26,매출액(수익),722.168679,847.499866,775.627411,892.707520,940.858114
27,........장기매입채무,NaN,NaN,NaN,NaN,NaN
28,........매입채무＜전기＞,23.281550,32.260400,57.070230,44.380450,72.098120
29,........매입채무＜당기＞,32.260400,57.070230,44.380450,72.098120,87.085700

In [16]:
# 한국전자금융 연간 가치분석 투자지표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.IV,
             subType=nf.IVType.VALUEABLE,
             period=nf.Period.YEAR)

https://navercomp.wisereport.co.kr/v2/company/cF4002.aspx?cmp_cd=063570&frq=0&rpt=5&finGubun=MAIN&frqTyp=0&cn=&encparam=ZjdhWXV2RTlsamFPNjc0TXFIQlloQT09

,account_nm,2018/12,2019/12,2020/12,2021/12,2022/12
0,EPS,6.208630e+02,7.814067e+01,1.012457e+02,2.713525e+02,2.505957e+02
1,당기순이익(지배)＜당기＞,2.104047e+02,2.683999e+01,3.457311e+01,9.266070e+01,8.557273e+01
2,보통주수정평균발행주식수＜당기＞,3.388906e+07,3.434829e+07,3.414773e+07,3.414773e+07,3.414773e+07
3,우선주수정평균발행주식수＜당기＞,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,BPS,5.192379e+03,5.096289e+03,5.106150e+03,5.444392e+03,5.746513e+03
5,자본총계(지배)＜당기＞,1.574868e+03,1.545723e+03,1.548714e+03,1.651304e+03,1.742938e+03
6,보통주수정기말발행주식수(자사주차감)＜당기＞,3.033037e+07,3.033037e+07,3.033037e+07,3.033037e+07,3.033037e+07
7,우선주수정기말발행주식수(자사주차감)＜당기＞,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
8,CPS,5.845595e+02,1.502525e+03,1.543577e+03,1.940842e+03,2.050753e+03
9,영업활동현금흐름＜당기＞,1.981017e+02,5.160915e+02,5.270965e+02,6.627533e+02,7.002857e+02
10,보통주수정평균발행주식수＜당기＞,3.388906e+07,3.434829e+07,3.414773e+07,3.414773e+07,3.414773e+07
11,우선주수정평균발행주식수＜당기＞,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
12,SPS,8.687862e+03,8.120263e+03,6.614514e+03,6.980387e+03,8.460687e+03
13,매출액＜당기＞,2.944235e+03,2.789172e+03,2.258706e+03,2.383644e+03,2.889132e+03
14,보통주수정평균발행주식수＜당기＞,3.388906e+07,3.434829e+07,3.414773e+07,3.414773e+07,3.414773e+07
15,우선주수정평균발행주식수＜당기＞,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
16,PER,1.447984e+01,9.981998e+01,5.649622e+01,2.019514e+01,1.831636e+01
17,보통주.수정주가(기말)＜당기＞,8.990000e+03,7.800000e+03,5.720000e+03,5.480000e+03,4.590000e+03
18,EPS＜당기＞,6.208630e+02,7.814067e+01,1.012457e+02,2.713525e+02,2.505957e+02
19,PBR,1.731380e+00,1.530530e+00,1.120220e+00,1.006540e+00,7.987500e-01
20,보통주.수정주가(기말)＜당기＞,8.990000e+03,7.800000e+03,5.720000e+03,5.480000e+03,4.590000e+03
21,BPS＜당기＞,5.192379e+03,5.096289e+03,5.106150e+03,5.444392e+03,5.746513e+03
22,PCR,1.537910e+01,5.191260e+00,3.705680e+00,2.823520e+00,2.238200e+00
23,보통주.수정주가(기말)＜당기＞,8.990000e+03,7.800000e+03,5.720000e+03,5.480000e+03,4.590000e+03
24,CPS＜당기＞,5.845595e+02,1.502525e+03,1.543577e+03,1.940842e+03,2.050753e+03
25,PSR,1.034780e+00,9.605600e-01,8.647600e-01,7.850600e-01,5.425100e-01
26,보통주.수정주가(기말)＜당기＞,8.990000e+03,7.800000e+03,5.720000e+03,5.480000e+03,4.590000e+03
27,SPS＜당기＞,8.687862e+03,8.120263e+03,6.614514e+03,6.980387e+03,8.460687e+03
28,EV/EBITDA,5.899680e+00,5.579790e+00,4.641780e+00,4.555980e+00,3.740910e+00
29,EV＜당기＞,3.113264e+03,3.445875e+03,3.037709e+03,3.249407e+03,2.985222e+03
30,EBITDA＜당기＞,5.277000e+02,6.175633e+02,6.544271e+02,7.132185e+02,7.979946e+02
31,DPS,1.100000e+02,1.100000e+02,1.100000e+02,1.100000e+02,1.100000e+02
32,현금DPS,1.100000e+02,1.100000e+02,1.100000e+02,1.100000e+02,1.100000e+02
33,주식DPS,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
34,현금배당수익률,1.223580e+00,1.410260e+00,1.923080e+00,2.007300e+00,2.396510e+00
35,현금배당성향(%),1.585678e+01,1.243048e+02,9.650100e+01,3.600599e+01,3.898836e+01

In [17]:
# 한국전자금융 분기 가치분석 투자지표
nf.crawl_nfn(stock_code=CORP[0],
             type=nf.DataType.IV,
             subType=nf.IVType.VALUEABLE,
             period=nf.Period.QUARTER)

https://navercomp.wisereport.co.kr/v2/company/cF4002.aspx?cmp_cd=063570&frq=1&rpt=5&finGubun=MAIN&frqTyp=1&cn=&encparam=RlR0QVdUR1U0clVwN1RoQno4bFVzQT09

,account_nm,2022/09,2022/12,2023/03,2023/06,2023/09
0,EPS,5.106890e+01,1.332154e+02,4.664622e+01,1.127943e+02,4.808066e+01
1,당기순이익(지배)＜당기＞,1.743887e+01,4.549003e+01,1.592862e+01,3.851669e+01,1.641845e+01
2,보통주수정평균발행주식수＜당기＞,3.414773e+07,3.414773e+07,3.414773e+07,3.414773e+07,3.414773e+07
3,우선주수정평균발행주식수＜당기＞,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,BPS,5.505043e+03,5.746513e+03,5.693221e+03,5.770217e+03,5.822202e+03
5,자본총계(지배)＜당기＞,1.669700e+03,1.742938e+03,1.726775e+03,1.750128e+03,1.765895e+03
6,보통주수정기말발행주식수(자사주차감)＜당기＞,3.033037e+07,3.033037e+07,3.033037e+07,3.033037e+07,3.033037e+07
7,우선주수정기말발행주식수(자사주차감)＜당기＞,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
8,CPS,5.753487e+02,4.837120e+02,4.419073e+01,5.734086e+02,5.327938e+02
9,영업활동현금흐름＜당기＞,1.964685e+02,1.651767e+02,1.509013e+01,1.958060e+02,1.819370e+02
10,보통주수정평균발행주식수＜당기＞,3.414773e+07,3.414773e+07,3.414773e+07,3.414773e+07,3.414773e+07
11,우선주수정평균발행주식수＜당기＞,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
12,SPS,2.114837e+03,2.481863e+03,2.271388e+03,2.614252e+03,2.755258e+03
13,매출액＜당기＞,7.221687e+02,8.474999e+02,7.756274e+02,8.927075e+02,9.408581e+02
14,보통주수정평균발행주식수＜당기＞,3.414773e+07,3.414773e+07,3.414773e+07,3.414773e+07,3.414773e+07
15,우선주수정평균발행주식수＜당기＞,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
16,PER,2.304209e+01,1.831636e+01,1.730260e+01,1.992873e+01,1.755022e+01
17,보통주.수정주가(기말)＜당기＞,4.650000e+03,4.590000e+03,5.050000e+03,6.850000e+03,5.980000e+03
18,EPS＜당기＞,2.018046e+02,2.505957e+02,2.918636e+02,3.437248e+02,3.407366e+02
19,PBR,8.446800e-01,7.987500e-01,8.870200e-01,1.187130e+00,1.027100e+00
20,보통주.수정주가(기말)＜당기＞,4.650000e+03,4.590000e+03,5.050000e+03,6.850000e+03,5.980000e+03
21,BPS＜당기＞,5.505043e+03,5.746513e+03,5.693221e+03,5.770217e+03,5.822202e+03
22,PCR,2.184190e+00,2.238200e+00,3.032340e+00,4.085500e+00,3.659500e+00
23,보통주.수정주가(기말)＜당기＞,4.650000e+03,4.590000e+03,5.050000e+03,6.850000e+03,5.980000e+03
24,CPS＜당기＞,2.128937e+03,2.050753e+03,1.665381e+03,1.676660e+03,1.634105e+03
25,PSR,5.830500e-01,5.425100e-01,5.616900e-01,7.224000e-01,5.907500e-01
26,보통주.수정주가(기말)＜당기＞,4.650000e+03,4.590000e+03,5.050000e+03,6.850000e+03,5.980000e+03
27,SPS＜당기＞,7.975358e+03,8.460687e+03,8.990770e+03,9.482339e+03,1.012276e+04
28,EV/EBITDA,1.460336e+01,1.402531e+01,1.597993e+01,1.709749e+01,1.619846e+01
29,EV＜당기＞,2.918094e+03,2.985222e+03,3.232345e+03,3.898557e+03,3.599296e+03
30,EBITDA＜당기＞,1.998235e+02,2.128453e+02,2.022753e+02,2.280192e+02,2.221999e+02
31,DPS,0.000000e+00,1.100000e+02,NaN,NaN,NaN
32,현금DPS,0.000000e+00,1.100000e+02,NaN,NaN,NaN
33,주식DPS,NaN,NaN,NaN,NaN,NaN
34,현금배당수익률,0.000000e+00,2.396514e+00,NaN,NaN,NaN
35,현금배당성향(%),0.000000e+00,7.334223e+01,NaN,NaN,NaN